root: [url]
services:
  - type: web
    name: ml-service
    runtime: python
    root: url  # Critical for mono-repo setup
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    plan: standard-1x
    healthCheckPath: /health
    autoDeploy: true