services:
  - type: web
    name: phishing-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 2 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT --timeout 180 --preload
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ML_SERVICE_URL   # Set this to your ML service URL after deployment
        sync: false
    plan: free
    healthCheckPath: /
    autoDeploy: true